
#pragma once

#define SERIAL_BAUDRATE 9600

#define DEBOUNCE_TIME 50
#define DIRECTION_CHANGE_DELAY 500

#define BRIDGE_ENABLE_PIN 2
#define BRIDGE_THRUST_PORT 3
#define BRIDGE_THRUST_STAR 4
#define BRIDGE_WINDLASS_UP 5
#define BRIDGE_WINDLASS_DOWN 6

#define COCKPIT_ENABLE_PIN 7
#define COCKPIT_THRUST_PORT 8
#define COCKPIT_THRUST_STAR 9
#define COCKPIT_WINDLASS_UP 10
#define COCKPIT_WINDLASS_DOWN 11

#define EMERGENCY_STOP_PIN 12

#define THRUSTER_PORT_RELAY 22
#define THRUSTER_STAR_RELAY 23

#define WINDLASS_UP_RELAY 24
#define WINDLASS_DOWN_RELAY 25

#define LED_READY 38
#define LED_ACTIVE 39
